goodweb:
    image: flaskwebserver
    container_name: legitweb
    ports:
        - "8080:5000"
        - "8443:443"
    expose:
        - "5000"
    environment:
        - APPLICATION_ROLE=legit

badweb:
    image: flaskwebserver
    container_name: evilweb
    ports:
        - "8081:5000"
        - "8444:443"
    expose:
        - "5000"
    environment:
        - APPLICATION_ROLE=evil
