version: "3.3"

services:
    legitweb:
        image: flaskwebserver
        container_name: legitweb
        hostname: legit
        ports:
            - "8080:5000"
            - "8443:443"
        expose:
            - "5000"
        volumes:
            - type: volume
              source: legit_ssl
              target: /opt/flask/ssl
#            - type: bind
#              source: ./webservers/flask/app
#              target: /opt/flask/app
        networks:
            nach.os:
                ipv4_address: 172.100.100.101
        environment:
            - APPLICATION_ROLE=legit

    evilweb:
        image: flaskwebserver
        container_name: evilweb
        hostname: evil
        ports:
            - "8081:5000"
            - "8444:443"
        expose:
            - "5000"
        volumes:
            - type: volume
              source: evil_ssl
              target: /opt/flask/ssl
#            - type: bind
#              source: ./webservers/flask/app
#              target: /opt/flask/app
        networks:
            nach.os:
                ipv4_address: 172.100.100.202
        environment:
            - APPLICATION_ROLE=evil

    dns:
        image: dnsmasq
        container_name: dns
        hostname: dns
        ports:
            - "53:53"
        expose:
            - "53"
        environment:
            - LEGIT_IP=172.100.100.101
            - LEGIT_DNSNAME=legit.nach.os
            - EVIL_IP=172.100.100.101
            - EVIL_DNSNAME=evil.nach.os

volumes:
    legit_ssl:
        external: true
    evil_ssl:
        external: true

networks:
    nach.os:
        driver: bridge
        ipam:
            driver: default
            config:
              - subnet: 172.100.100.0/24
