goodweb:
    image: goodguywebserver
    container_name: goodguyweb
    ports:
        - "8080:80"
        - "8443:443"
    expose:
        - "80"
    environment:
        - NGINX_HOST=goodguy.nach.os

badweb:
    image: badguywebserver
    container_name: badguyweb
    ports:
        - "8081:80"
        - "8444:443"
    expose:
        - "80"
    environment:
        - NGINX_HOST=goodguy.nach.os
