version: "3.3"

services:
    goodweb:
        image: flaskwebserver
        container_name: legitweb
        ports:
            - "8080:5000"
            - "8443:443"
        expose:
            - "5000"
        volumes:
            - type: volume
              source: legit_ssl
              target: /opt/flask/ssl
        environment:
            - APPLICATION_ROLE=legit

    badweb:
        image: flaskwebserver
        container_name: evilweb
        ports:
            - "8081:5000"
            - "8444:443"
        expose:
            - "5000"
        volumes:
            - type: volume
              source: evil_ssl
              target: /opt/flask/ssl
        environment:
            - APPLICATION_ROLE=evil

volumes:
    legit_ssl:
        external: true
    evil_ssl:
        external: true
